### ISSUE TITLE
Problem about publicPath if not set in file-loader's options

### ISSUE THREAD

**Issue by meteorlxy** [webpack-contrib/file-loader#286]
* Operating System: Windows 10 x64 Pro & Ubuntu 18.04
* Node Version:  v10.6.0 & v8.11.1
* NPM Version:  v6.1.0 & v5.8.0
* webpack Version: v4.15.1 & v3.12.0
* file-loader Version: v1.1.11

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

#### Webpack config

With `publicPath` in `output`

https://github.com/meteorlxy/repro-file-loader-bug/blob/c23b2a9a6818ea697a5ac382e738bd21a2e2d07b/build/webpack.base.conf.js#L21

but no `publicPath` in `file-loader`'s `options`
https://github.com/meteorlxy/repro-file-loader-bug/blob/c23b2a9a6818ea697a5ac382e738bd21a2e2d07b/build/webpack.base.conf.js#L43-L49

#### Use case in Vue

Introduce same image in both `img:src` and `background-image: url()`

https://github.com/meteorlxy/repro-file-loader-bug/blob/c23b2a9a6818ea697a5ac382e738bd21a2e2d07b/src/App.vue#L3
https://github.com/meteorlxy/repro-file-loader-bug/blob/c23b2a9a6818ea697a5ac382e738bd21a2e2d07b/src/App.vue#L23

#### Expected Behavior

Both of them have `publicPath` after compiling.

#### Actual Behavior

`background-image: url()` is compiled with `publicPath` correctly, but `img:src` is not.

https://github.com/meteorlxy/repro-file-loader-bug/blob/c23b2a9a6818ea697a5ac382e738bd21a2e2d07b/dist/static/css/app.7b93833f36168b8a692548c3f4b678cc.css#L1
![image](https://user-images.githubusercontent.com/18205362/42683281-71a4a640-86bf-11e8-88fe-f3eb6010e64f.png)

https://github.com/meteorlxy/repro-file-loader-bug/blob/c23b2a9a6818ea697a5ac382e738bd21a2e2d07b/dist/static/js/app.70725e77e25aa8a5765f.js#L1
![image](https://user-images.githubusercontent.com/18205362/42683243-59d2c22c-86bf-11e8-8e58-c4465c775763.png)

### How Do We Reproduce?

For fast repro, I generate a new Vue project via the cli & template.

Repro repo: https://github.com/meteorlxy/repro-file-loader-bug

I have also uploaded the `dist` files.

To build again:
```
yarn
yarn build
```

Then check the production files `dist/static/js/app.xxx.js` and `dist/static/css/app.xxx.css`

### What's more

If I set `publicPath` in `file-loader`'s `options` again, it works well.

But if I don't set `publicPath` in `file-loader`, and let `file-loader` to use `__webpack_public_path__`, this bug appears.

**Comment by chrisckc** [comment]
Noticed this when trying to get Aurelia app to run under a sub path of root.

I set `publicPath = '/app'` in webpack config
After performing the webpack build into the 'dist' dir, I noticed that the extracted font-awesome css file contained incorrect references to the fontawesome eot file:
`src: url(/app674f50d287a8c48dc19ba404d20fe713.eot);`
Notice that the /'app' path has been prepended to the filename with no '/' path separator.

If i change the publicPath to '/app/' (adding a trailing slash) the issue goes away but then requires the trailing slash to be added to the url when accessing the site via the webpack dev server which does not fit well what i am trying to do.

I believe this is an issue with this plugin rather than a requirement to use a trailing slash when using publicPath.

To fix this i have `const baseUrl = '/app';` defined outside of the config and set both publicPath and the file-loader options to it.

```
{ test: /\.(ttf|eot|svg|otf)(\?v=[0-9]\.[0-9]\.[0-9])?$/i, 
        loader: 'file-loader',
        options: {
            name: '[name].[hash].[ext]',
            publicPath: baseUrl // fixes issue where public path is prepended to the filename without '/' separator
        }, 
      },
```

**Comment by chrisckc** [comment]
example repo details can be found here:
https://github.com/webpack-contrib/url-loader/issues/164

**Comment by chrisckc** [comment]
Seems that this is just an issue with file-loader due to the way url-loader works (falls back to file-loader for files larger than limit)

According to the file-loader docs, file-loader defaults publicPath to 'webpack_public_path' which is the same as output.publicPath so there should really be no difference in behaviour when specifying the exact same publicPath in file-loader options.

I have worked around the issue and its no longer affecting that i was trying to do but thought it was worth mentioning here due to the inconsistent behaviour that others may also encounter.

The behaviour can be seen by following the repo instructions i posted in this issue: https://github.com/webpack-contrib/url-loader/issues/164

**Comment by evilebottnawi** [comment]
@chrisckc can you create **minimum** reproducible test repo and describe what you have and what you expected in README, it is hard to understand what you mean

**Comment by chrisckc** [comment]
Here we are:
https://github.com/chrisckc/webpack-starter-basic
Instructions in the Readme.

I used one of the webpack starter projects to save time in creating the minimum reproducible test repo, yes it could be more minimum but that's that. Same behaviour in 2 separate projects so far.

**Comment by evilebottnawi** [comment]
@meteorlxy not related to `file-loader`, please create issue in `vue-loader`

**Comment by evilebottnawi** [comment]
@chrisckc please don't write not related problems in other issue, one problem = one issue, also i can't run you minimum reproducible test repo.

@chrisckc please read documentation https://webpack.js.org/configuration/output/#output-publicpath 

The `publichPath` option should be end on `/`. Why? In some cases webserver can handle assets not as filesystem (example `/assets/minify-file.png` and you should setup `/assets/minify-` for `publichPath` option) so we can allow people to setup this, it is very rare cases, but we have a lot of developers and should be maximum flexibility. For this we add to documentation some limitation notes. Here you can see :
```
The value of the option is prefixed to every URL created by the runtime or loaders. Because of this the value of this option ends with / in most cases.
```
