### ISSUE TITLE
Dynamic contexts & naming

### ISSUE THREAD

**Issue by brenwell** [webpack-contrib/file-loader#34]
Hey there, thanks for all the hard work.

I was wondering if it was possible to have control over the naming when using the **file-loader** width dynamic requires.
##### This code

``` coffeescript
path = require 'themes/' + themeCode + '/locale/' + languageCode + '.json'
```
##### With this dir structure

```
/src/themes/civic/locale/en.json
```
##### With this config

``` coffeescript
{test: /\.json$/, loader: "file-loader"}
```
##### Results in

```
/build/03f272c55f8da7ff3616a17654816467.json
```
##### With this config instead

``` coffeescript
{test: /\.json$/, loader: "file-loader?name=[path][name].[ext]"}
```
##### It results in

```
/build/src/themes/civic/locale/en.json
```
##### I was curious if there was a way to get a result such as

```
/build/locales/civic/en.json
```
##### perhaps there is away to get the context variables

``` coffeescript
{test: /\.json$/, loader: "file-loader?name=locales/[context[0]]/[context[1]].[ext]"}
```

Thanks for any feedback

**Comment by babygau** [comment]
Could you try

```js
{test: /\.json$/, loader: "file-loader?name=locales/civic/[name].[ext]"}
```

**Comment by barroudjo** [comment]
I tried 
`{test: /\.json$/, loader: "file-loader?name=[path][name].[ext]&context=../.."}`
But it turned out that it works differently in windows and in linux...
So i'm also looking for a response to this question: how to keep only a part of the path ? This probably involes using a 'context' query parameter, but how ?
