### ISSUE TITLE
how to build with transform to lowercase name ?

### ISSUE THREAD

**Issue by DragorWW** [webpack-contrib/file-loader#69]

**Comment by dmorrison42** [comment]
Unfortunately, there is not much information provided on this ticket, but I believe I am having this issue as well.

The block below shows what I am trying to do. Obviously the `toLowerCase` call does not work property because [name] is not evaluated until after the call.

```javascript
module.exports = {
    entry: {
        'myAjax': './myajax.js',
    },
    output: {
        filename: '[name].js'.toLowerCase(),
        library: ['myModule', '[name]'],
        path: 'dst',
    },
};
```

I am currently working around this by creating a array of objects for the exports with one entry per object.

Is there a cleaner way of doing this?

**Comment by luchsamapparat** [comment]
I posted a possible solution for your problem in [this issue](#issuecomment-257981311)

**Comment by johnhforrest** [comment]
You can write a custom loader that modifies the result of file-loader.

For example:

```
// lowercase-file.js

module.exports = function (content) {
    return content.toLowerCase();
};
```

Then, in your config, chain this new loader with the output from file-loader:

```
loaders: [
  {
    test: /.html$/,
    loaders: ['lowercase-file', 'file']
  }
]
```

**Comment by evilebottnawi** [comment]
@DragorWW @dmorrison42 @luchsamapparat @johnhforrest 
Use `name` as `function`.
```shell
{
    loader: 'file-loader',
    options: {
        name: function (resourcePath) {
            return myRenameFunction(resourcePath);
    }
}
```

**Comment by michael-ciniawsky** [comment]
See @evilebottnawi's comment, feel free to reopen if still regressions :)

**Comment by pbrain19** [comment]
this needs to be documented asap!

**Comment by evilebottnawi** [comment]
@pbrain19 PR welcome, we supporting large ecosystem for `webpack` and it is difficult found time on all
